{% set name = "naaf" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/naaf-{{ version }}.tar.gz
  sha256: 8edfecdb2eac14bf4c12e2fc31b5eba9a0a286308e9e0e19c7f195426d1ca1ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - dask-core
    - dynamotable >=0.2.4
    - emfile >=0.3
    - ipython
    - mrcfile >=1.3.0
    - numpy
    - pandas
    - pydantic
    - python >=3.8
    - scipy
    - starfile >=0.4.5

test:
  imports:
    - naaf
  commands:
    - pip list
    # - pip check  # This can be uncommente when pinnings are relaxed upstream
  requires:
    - pip

about:
  home: https://github.com/gutsche-lab/naaf
  summary: IO hub for Cryo-EM, Cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brisvag
    - goanpeca
